# Generated by Django 5.0.6 on 2024-05-13 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateDetails",
            fields=[
                ("candidate_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("age", models.PositiveIntegerField()),
                ("exp", models.PositiveIntegerField()),
                ("domain", models.CharField(max_length=100)),
                ("skills", models.JSONField()),
                ("technologies", models.JSONField()),
                ("resume_link", models.URLField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
