# Generated by Django 5.0.6 on 2024-05-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatedetails",
            name="education",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
