# Generated by Django 5.0.6 on 2024-05-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0003_candidatedetails_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatedetails",
            name="resume_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
