# Generated by Django 5.0.6 on 2024-05-18 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0002_jobposting"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="company_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_postings",
                to="adminapp.companyprofile",
            ),
        ),
    ]
