# Generated by Django 5.0.6 on 2024-05-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0005_jobapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="score",
            field=models.TextField(),
        ),
    ]
