# Generated by Django 5.0.6 on 2024-05-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0007_jobapplication_score_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="skills_new",
            field=models.TextField(blank=True, null=True),
        ),
    ]
