# Generated by Django 5.0.6 on 2024-05-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0009_remove_jobapplication_technologies"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={"managed": False},
        ),
    ]
