# Generated by Django 5.0.6 on 2024-05-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0010_alter_jobapplication_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={},
        ),
    ]
